In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/Pokemon.csv').rename(columns={'#': 'Number', 'Sp. Atk': 'Spatk', 'Sp. Def': 'Spdef', 'Type 1': 'Type1', 'Type 2': 'Type2'})

In [3]:
df.head()

,Number,Name,Type1,Type2,Total,HP,Attack,Defense,Spatk,Spdef,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [4]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.impute import SimpleImputer

In [5]:
df['Type1'] = df['Type1'].astype(str)
df['Type2'] = df['Type2'].astype(str)

In [6]:
imp = SimpleImputer()
si = SimpleImputer(strategy='constant', fill_value='Pure')

In [7]:
df['Type2'].isna().sum()

np.int64(386)

In [8]:
df['Type2'] = si.fit_transform(df[['Type2']]).ravel()

In [9]:
y = ['Legendary']

In [10]:
onehot_type1 = OneHotEncoder(sparse_output=False)
onehot_type2 = OneHotEncoder(sparse_output=False)

In [11]:
onehot_type2.fit_transform(df[['Type1']])

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(800, 18))

In [12]:
df_encoded_type1 = pd.DataFrame(onehot_type1.fit_transform(df[['Type1']]), columns=onehot_type1.get_feature_names_out(['Type1']))

In [13]:
df.head()

,Number,Name,Type1,Type2,Total,HP,Attack,Defense,Spatk,Spdef,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,Pure,309,39,52,43,60,50,65,1,False

In [14]:
df_encoded_type1.head()

,Type1_Bug,Type1_Dark,Type1_Dragon,Type1_Electric,Type1_Fairy,Type1_Fighting,Type1_Fire,Type1_Flying,Type1_Ghost,Type1_Grass,Type1_Ground,Type1_Ice,Type1_Normal,Type1_Poison,Type1_Psychic,Type1_Rock,Type1_Steel,Type1_Water
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
df_encoded_type2 = pd.DataFrame(onehot_type2.fit_transform(df[['Type2']]), columns=onehot_type2.get_feature_names_out(['Type2']))

In [16]:
df_encoded_type2.head()

,Type2_Bug,Type2_Dark,Type2_Dragon,Type2_Electric,Type2_Fairy,Type2_Fighting,Type2_Fire,Type2_Flying,Type2_Ghost,Type2_Grass,Type2_Ground,Type2_Ice,Type2_Normal,Type2_Poison,Type2_Psychic,Type2_Pure,Type2_Rock,Type2_Steel,Type2_Water
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [17]:
df_enc = pd.concat([df_encoded_type1, df_encoded_type2], axis=1)

In [18]:
columns_encoded = list(df_enc.columns)

In [19]:
df_enc.head()

,Type1_Bug,Type1_Dark,Type1_Dragon,Type1_Electric,Type1_Fairy,Type1_Fighting,Type1_Fire,Type1_Flying,Type1_Ghost,Type1_Grass,...,Type2_Grass,Type2_Ground,Type2_Ice,Type2_Normal,Type2_Poison,Type2_Psychic,Type2_Pure,Type2_Rock,Type2_Steel,Type2_Water
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [20]:
to_std_features = ['Total', 'HP', 'Attack', 'Defense', 'Spatk', 'Spdef', 'Speed']

In [21]:
to_std_features = ['Total']
sc = StandardScaler()
df[to_std_features] = sc.fit_transform(df[to_std_features])

In [22]:
df[to_std_features] = sc.fit_transform(df[to_std_features])

In [23]:
df.head()

,Number,Name,Type1,Type2,Total,HP,Attack,Defense,Spatk,Spdef,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,-0.976765,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,-0.251088,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,0.749845,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,1.583957,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,Pure,-1.051836,39,52,43,60,50,65,1,False

In [24]:
df = pd.concat([df, df_enc], axis=1)
df.head()

,Number,Name,Type1,Type2,Total,HP,Attack,Defense,Spatk,Spdef,...,Type2_Grass,Type2_Ground,Type2_Ice,Type2_Normal,Type2_Poison,Type2_Psychic,Type2_Pure,Type2_Rock,Type2_Steel,Type2_Water
0,1,Bulbasaur,Grass,Poison,-0.976765,45,49,49,65,65,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,2,Ivysaur,Grass,Poison,-0.251088,60,62,63,80,80,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,3,Venusaur,Grass,Poison,0.749845,80,82,83,100,100,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,3,VenusaurMega Venusaur,Grass,Poison,1.583957,80,100,123,122,120,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,4,Charmander,Fire,Pure,-1.051836,39,52,43,60,50,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [25]:
le_tgt = LabelEncoder()

In [26]:
df = df.assign(y_enc = le_tgt.fit_transform(df['Legendary'].values.ravel()))

In [27]:
df['Legendary'].unique()

array([False,  True])

In [28]:
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.model_selection import train_test_split

In [29]:
features = ['Total', 'HP', 'Attack', 'Defense', 'Spatk', 'Spdef', 'Speed']

In [30]:
features

['Total', 'HP', 'Attack', 'Defense', 'Spatk', 'Spdef', 'Speed']

In [31]:
X_train, X_test, y_train, y_test = train_test_split(df[features+columns_encoded], df[['y_enc']], test_size=0.1, random_state=42)

In [32]:
df

,Number,Name,Type1,Type2,Total,HP,Attack,Defense,Spatk,Spdef,...,Type2_Ground,Type2_Ice,Type2_Normal,Type2_Poison,Type2_Psychic,Type2_Pure,Type2_Rock,Type2_Steel,Type2_Water,y_enc
0,1,Bulbasaur,Grass,Poison,-0.976765,45,49,49,65,65,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
1,2,Ivysaur,Grass,Poison,-0.251088,60,62,63,80,80,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
2,3,Venusaur,Grass,Poison,0.749845,80,82,83,100,100,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
3,3,VenusaurMega Venusaur,Grass,Poison,1.583957,80,100,123,122,120,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
4,4,Charmander,Fire,Pure,-1.051836,39,52,43,60,50,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,1.375429,50,100,150,100,150,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
796,719,DiancieMega Diancie,Rock,Fairy,2.209541,50,160,110,160,110,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
797,720,HoopaHoopa Confined,Psychic,Ghost,1.375429,80,110,60,150,130,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
798,720,HoopaHoopa Unbound,Psychic,Dark,2.042718,80,160,60,170,130,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
799,721,Volcanion,Fire,Water,1.375429,80,110,120,130,90,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1

In [33]:
model = HistGradientBoostingClassifier()
model = model.fit(X=X_train, y=y_train.to_numpy().ravel())
model.predict(X_test)

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
model.predict(X_test)

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
to_predict_true = y_test.assign(pred=model.predict(X_test)).loc[lambda x: x['y_enc']==1].index

In [36]:
predicted_true = y_test.assign(pred=model.predict(X_test)).loc[lambda x: x['pred']==1].index

In [37]:
df.iloc[to_predict_true]['Name']

796     DiancieMega Diancie
423                 Groudon
422     KyogrePrimal Kyogre
545    GiratinaOrigin Forme
795                 Diancie
Name: Name, dtype: str

In [38]:
df.iloc[predicted_true]['Name']

696               Hydreigon
23      PidgeotMega Pidgeot
796     DiancieMega Diancie
423                 Groudon
422     KyogrePrimal Kyogre
545    GiratinaOrigin Forme
Name: Name, dtype: str

In [39]:
from sklearn.metrics import classification_report

In [40]:
print(classification_report(y_test, model.predict(X_test)))

              precision    recall  f1-score   support

           0       0.99      0.97      0.98        75
           1       0.67      0.80      0.73         5

    accuracy                           0.96        80
   macro avg       0.83      0.89      0.85        80
weighted avg       0.97      0.96      0.96        80

In [41]:
from sklearn.pipeline import Pipeline, make_pipeline, make_union

In [42]:
from skrub import SelectCols

In [43]:
num_features = ['Total', 'HP', 'Attack', 'Defense', 'Spatk', 'Spdef', 'Speed']
features = num_features + ['Type1', 'Type2']

In [44]:
type2_pipeline = make_pipeline(SelectCols('Type2'), SimpleImputer(missing_values='nan', strategy='constant', fill_value='Pure'), OneHotEncoder(handle_unknown='infrequent_if_exist', sparse_output=False))
type1_pipeline = make_pipeline(SelectCols('Type1'), OneHotEncoder(handle_unknown='infrequent_if_exist',sparse_output=False))
numeric_pipeline = make_pipeline(SelectCols(num_features), StandardScaler())

In [45]:
type2_pipeline

Pipeline(steps=[('selectcols', SelectCols(cols='Type2')),
                ('simpleimputer',
                 SimpleImputer(fill_value='Pure', missing_values='nan',
                               strategy='constant')),
                ('onehotencoder',
                 OneHotEncoder(handle_unknown='infrequent_if_exist',
                               sparse_output=False))])

In [46]:
type1_pipeline

Pipeline(steps=[('selectcols', SelectCols(cols='Type1')),
                ('onehotencoder',
                 OneHotEncoder(handle_unknown='infrequent_if_exist',
                               sparse_output=False))])

In [47]:
Features = make_union(type2_pipeline, type1_pipeline, numeric_pipeline)

In [48]:
Features

FeatureUnion(transformer_list=[('pipeline-1',
                                Pipeline(steps=[('selectcols',
                                                 SelectCols(cols='Type2')),
                                                ('simpleimputer',
                                                 SimpleImputer(fill_value='Pure',
                                                               missing_values='nan',
                                                               strategy='constant')),
                                                ('onehotencoder',
                                                 OneHotEncoder(handle_unknown='infrequent_if_exist',
                                                               sparse_output=False))])),
                               ('pipeline-2',
                                Pipeline(steps=[('selectcols',
                                                 SelectCols(cols='Type1')),
                                                ('onehotencoder',
                                                 OneHotEncoder(handle_unknown='infrequent_if_exist',
                                                               sparse_output=False))])),
                               ('pipeline-3',
                                Pipeline(steps=[('selectcols',
                                                 SelectCols(cols=['Total', 'HP',
                                                                  'Attack',
                                                                  'Defense',
                                                                  'Spatk',
                                                                  'Spdef',
                                                                  'Speed'])),
                                                ('standardscaler',
                                                 StandardScaler())]))])

In [49]:
X_train, X_test, y_train, y_test = train_test_split(df[features], df['Legendary'], test_size=0.1, random_state=42)
le_encoder = LabelEncoder()
y_train_e, y_test_e = le_encoder.fit_transform(y_train), le_encoder.transform(y_test)

In [50]:
# Features.fit_transform(X_train, y_train_e)

In [51]:
e2e_pipe = make_pipeline(Features, HistGradientBoostingClassifier())

In [52]:
e2e_pipe

Pipeline(steps=[('featureunion',
                 FeatureUnion(transformer_list=[('pipeline-1',
                                                 Pipeline(steps=[('selectcols',
                                                                  SelectCols(cols='Type2')),
                                                                 ('simpleimputer',
                                                                  SimpleImputer(fill_value='Pure',
                                                                                missing_values='nan',
                                                                                strategy='constant')),
                                                                 ('onehotencoder',
                                                                  OneHotEncoder(handle_unknown='infrequent_if_exist',
                                                                                sparse_output=False))])),
                                                ('pipeline-2',
                                                 Pipeline(steps=[('...
                                                                  SelectCols(cols='Type1')),
                                                                 ('onehotencoder',
                                                                  OneHotEncoder(handle_unknown='infrequent_if_exist',
                                                                                sparse_output=False))])),
                                                ('pipeline-3',
                                                 Pipeline(steps=[('selectcols',
                                                                  SelectCols(cols=['Total',
                                                                                   'HP',
                                                                                   'Attack',
                                                                                   'Defense',
                                                                                   'Spatk',
                                                                                   'Spdef',
                                                                                   'Speed'])),
                                                                 ('standardscaler',
                                                                  StandardScaler())]))])),
                ('histgradientboostingclassifier',
                 HistGradientBoostingClassifier())])

In [53]:
e2e_pipe.get_params()

{'memory': None,
 'steps': [('featureunion',
   FeatureUnion(transformer_list=[('pipeline-1',
                                   Pipeline(steps=[('selectcols',
                                                    SelectCols(cols='Type2')),
                                                   ('simpleimputer',
                                                    SimpleImputer(fill_value='Pure',
                                                                  missing_values='nan',
                                                                  strategy='constant')),
                                                   ('onehotencoder',
                                                    OneHotEncoder(handle_unknown='infrequent_if_exist',
                                                                  sparse_output=False))])),
                                  ('pipeline-2',
                                   Pipeline(steps=[('selectcols',
                                                    SelectCols(cols='Type1')),
                                                   ('onehotencoder',
                                                    OneHotEncoder(handle_unknown='infrequent_if_exist',
                                                                  sparse_output=False))])),
                                  ('pipeline-3',
                                   Pipeline(steps=[('selectcols',
                                                    SelectCols(cols=['Total', 'HP',
                                                                     'Attack',
                                                                     'Defense',
                                                                     'Spatk',
                                                                     'Spdef',
                                                                     'Speed'])),
                                                   ('standardscaler',
                                                    StandardScaler())]))])),
  ('histgradientboostingclassifier', HistGradientBoostingClassifier())],
 'transform_input': None,
 'verbose': False,
 'featureunion': FeatureUnion(transformer_list=[('pipeline-1',
                                 Pipeline(steps=[('selectcols',
                                                  SelectCols(cols='Type2')),
                                                 ('simpleimputer',
                                                  SimpleImputer(fill_value='Pure',
                                                                missing_values='nan',
                                                                strategy='constant')),
                                                 ('onehotencoder',
                                                  OneHotEncoder(handle_unknown='infrequent_if_exist',
                                                                sparse_output=False))])),
                                ('pipeline-2',
                                 Pipeline(steps=[('selectcols',
                                                  SelectCols(cols='Type1')),
                                                 ('onehotencoder',
                                                  OneHotEncoder(handle_unknown='infrequent_if_exist',
                                                                sparse_output=False))])),
                                ('pipeline-3',
                                 Pipeline(steps=[('selectcols',
                                                  SelectCols(cols=['Total', 'HP',
                                                                   'Attack',
                                                                   'Defense',
                                                                   'Spatk',
                                                                   'Spdef',
                                                                   'Speed'])),
                                                 ('standardscaler',
                                                  StandardScaler())]))]),
 'histgradientboostingclassifier': HistGradientBoostingClassifier(),
 'featureunion__n_jobs': None,
 'featureunion__transformer_list': [('pipeline-1',
   Pipeline(steps=[('selectcols', SelectCols(cols='Type2')),
                   ('simpleimputer',
                    SimpleImputer(fill_value='Pure', missing_values='nan',
                                  strategy='constant')),
                   ('onehotencoder',
                    OneHotEncoder(handle_unknown='infrequent_if_exist',
                                  sparse_output=False))])),
  ('pipeline-2',
   Pipeline(steps=[('selectcols', SelectCols(cols='Type1')),
                   ('onehotencoder',
                    OneHotEncoder(handle_unknown='infrequent_if_exist',
                                  sparse_output=False))])),
  ('pipeline-3',
   Pipeline(steps=[('selectcols',
                    SelectCols(cols=['Total', 'HP', 'Attack', 'Defense', 'Spatk',
                                     'Spdef', 'Speed'])),
                   ('standardscaler', StandardScaler())]))],
 'featureunion__transformer_weights': None,
 'featureunion__verbose': False,
 'featureunion__verbose_feature_names_out': True,
 'featureunion__pipeline-1': Pipeline(steps=[('selectcols', SelectCols(cols='Type2')),
                 ('simpleimputer',
                  SimpleImputer(fill_value='Pure', missing_values='nan',
                                strategy='constant')),
                 ('onehotencoder',
                  OneHotEncoder(handle_unknown='infrequent_if_exist',
                                sparse_output=False))]),
 'featureunion__pipeline-2': Pipeline(steps=[('selectcols', SelectCols(cols='Type1')),
                 ('onehotencoder',
                  OneHotEncoder(handle_unknown='infrequent_if_exist',
                                sparse_output=False))]),
 'featureunion__pipeline-3': Pipeline(steps=[('selectcols',
                  SelectCols(cols=['Total', 'HP', 'Attack', 'Defense', 'Spatk',
                                   'Spdef', 'Speed'])),
                 ('standardscaler', StandardScaler())]),
 'featureunion__pipeline-1__memory': None,
 'featureunion__pipeline-1__steps': [('selectcols', SelectCols(cols='Type2')),
  ('simpleimputer',
   SimpleImputer(fill_value='Pure', missing_values='nan', strategy='constant')),
  ('onehotencoder',
   OneHotEncoder(handle_unknown='infrequent_if_exist', sparse_output=False))],
 'featureunion__pipeline-1__transform_input': None,
 'featureunion__pipeline-1__verbose': False,
 'featureunion__pipeline-1__selectcols': SelectCols(cols='Type2'),
 'featureunion__pipeline-1__simpleimputer': SimpleImputer(fill_value='Pure', missing_values='nan', strategy='constant'),
 'featureunion__pipeline-1__onehotencoder': OneHotEncoder(handle_unknown='infrequent_if_exist', sparse_output=False),
 'featureunion__pipeline-1__selectcols__cols': 'Type2',
 'featureunion__pipeline-1__simpleimputer__add_indicator': False,
 'featureunion__pipeline-1__simpleimputer__copy': True,
 'featureunion__pipeline-1__simpleimputer__fill_value': 'Pure',
 'featureunion__pipeline-1__simpleimputer__keep_empty_features': False,
 'featureunion__pipeline-1__simpleimputer__missing_values': 'nan',
 'featureunion__pipeline-1__simpleimputer__strategy': 'constant',
 'featureunion__pipeline-1__onehotencoder__categories': 'auto',
 'featureunion__pipeline-1__onehotencoder__drop': None,
 'featureunion__pipeline-1__onehotencoder__dtype': numpy.float64,
 'featureunion__pipeline-1__onehotencoder__feature_name_combiner': 'concat',
 'featureunion__pipeline-1__onehotencoder__handle_unknown': 'infrequent_if_exist',
 'featureunion__pipeline-1__onehotencoder__max_categories': None,
 'featureunion__pipeline-1__onehotencoder__min_frequency': None,
 'featureunion__pipeline-1__onehotencoder__sparse_output': False,
 'featureunion__pipeline-2__memory': None,
 'featureunion__pipeline-2__steps': [('selectcols', SelectCols(cols='Type1')),
  ('onehotencoder',
   OneHotEncoder(handle_unknown='infrequent_if_exist', sparse_output=False))],
 'featureunion__pipeline-2__transform_input': None,
 'featureunion__pipeline-2__verbose': False,
 'featureunion__pipeline-2__selectcols': SelectCols(cols='Type1'),
 'featureunion__pipeline-2__onehotencoder': OneHotEncoder(handle_unknown='infrequent_if_exist', sparse_output=False),
 'featureunion__pipeline-2__selectcols__cols': 'Type1',
 'featureunion__pipeline-2__onehotencoder__categories': 'auto',
 'featureunion__pipeline-2__onehotencoder__drop': None,
 'featureunion__pipeline-2__onehotencoder__dtype': numpy.float64,
 'featureunion__pipeline-2__onehotencoder__feature_name_combiner': 'concat',
 'featureunion__pipeline-2__onehotencoder__handle_unknown': 'infrequent_if_exist',
 'featureunion__pipeline-2__onehotencoder__max_categories': None,
 'featureunion__pipeline-2__onehotencoder__min_frequency': None,
 'featureunion__pipeline-2__onehotencoder__sparse_output': False,
 'featureunion__pipeline-3__memory': None,
 'featureunion__pipeline-3__steps': [('selectcols',
   SelectCols(cols=['Total', 'HP', 'Attack', 'Defense', 'Spatk', 'Spdef', 'Speed'])),
  ('standardscaler', StandardScaler())],
 'featureunion__pipeline-3__transform_input': None,
 'featureunion__pipeline-3__verbose': False,
 'featureunion__pipeline-3__selectcols': SelectCols(cols=['Total', 'HP', 'Attack', 'Defense', 'Spatk', 'Spdef', 'Speed']),
 'featureunion__pipeline-3__standardscaler': StandardScaler(),
 'featureunion__pipeline-3__selectcols__cols': ['Total',
  'HP',
  'Attack',
  'Defense',
  'Spatk',
  'Spdef',
  'Speed'],
 'featureunion__pipeline-3__standardscaler__copy': True,
 'featureunion__pipeline-3__standardscaler__with_mean': True,
 'featureunion__pipeline-3__standardscaler__with_std': True,
 'histgradientboostingclassifier__categorical_features': 'from_dtype',
 'histgradientboostingclassifier__class_weight': None,
 'histgradientboostingclassifier__early_stopping': 'auto',
 'histgradientboostingclassifier__interaction_cst': None,
 'histgradientboostingclassifier__l2_regularization': 0.0,
 'histgradientboostingclassifier__learning_rate': 0.1,
 'histgradientboostingclassifier__loss': 'log_loss',
 'histgradientboostingclassifier__max_bins': 255,
 'histgradientboostingclassifier__max_depth': None,
 'histgradientboostingclassifier__max_features': 1.0,
 'histgradientboostingclassifier__max_iter': 100,
 'histgradientboostingclassifier__max_leaf_nodes': 31,
 'histgradientboostingclassifier__min_samples_leaf': 20,
 'histgradientboostingclassifier__monotonic_cst': None,
 'histgradientboostingclassifier__n_iter_no_change': 10,
 'histgradientboostingclassifier__random_state': None,
 'histgradientboostingclassifier__scoring': 'loss',
 'histgradientboostingclassifier__tol': 1e-07,
 'histgradientboostingclassifier__validation_fraction': 0.1,
 'histgradientboostingclassifier__verbose': 0,
 'histgradientboostingclassifier__warm_start': False}

In [54]:
y_pred = e2e_pipe.fit(X_train, y_train_e).predict(X_test)

In [55]:
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [56]:
print(classification_report(y_test_e, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.97      0.98        75
           1       0.67      0.80      0.73         5

    accuracy                           0.96        80
   macro avg       0.83      0.89      0.85        80
weighted avg       0.97      0.96      0.96        80